ingressRoute:
  dashboard:
    enabled: false
logs:
  general:
    level: DEBUG
    filePath: /var/log/traefik.log
  access:
    enabled: true
service:
  ## TODO: Change this if no LB are available or you need to use a specific IP for the Controllers
  # externalIPs:
  #   - 192.168.1.2
  #   - 172.10.10.10
  type: LoadBalancer # TODO!: Change this if no LB are available
deployment:
  replicas: 1
annotations:
  ## If using neuvector, uncomment the following lines
  # neuvector.com/scan: "true"
  # neuvector.com/scan-time: "300"
  # traefik.ingress.kubernetes.io/auth-type: "forward"
  # traefik.ingress.kubernetes.io/auth-response-headers: "X-Forwarded-User"
  # traefik.ingress.kubernetes.io/auth-url: "http://neuvector-controller-service.neuvector:1025/k8s_auth"
