controller:
  apisvc:
    type: ClusterIP
manager:
  svc:
    type: ClusterIP
  env:
    ssl: false
  ingress:
    enabled: true
    host: neuvector-ui.k8s
    ingressClassName: traefik
    path: "/"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
      # ingress.kubernetes.io/rewrite-target: /
    tls: false
