controller:
  apisvc:
    type: ClusterIP
manager:
  svc:
    type: ClusterIP
  env:
    ssl: true
  ingress:
    enabled: true
    host: <YOUR_DOMAIN> # TODO: Change this to your domain
    path: /
    ingressClassName: "nginx" # TODO: Change this to your ingress class
    annotations:
      cert-manager.io/cluster-issuer: "cloudflare-production"
    tls: "true"
    secretName: neuvector-tls

# TODO: If running from a K3s, uncommment the following lines
k3s:
  enabled: true
