controller:
  apisvc:
    type: ClusterIP
manager:
  svc:
    type: ClusterIP
  env:
    ssl: true
  ingress:
    enabled: true
    host: neuvector.k8s
    ingressClassName: nginx
    path: "/"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
      # ingress.kubernetes.io/rewrite-target: /
    tls:
      - hosts:
          - neuvector.k8s
        secretName: neuvector-tls
