### DOCS: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/

controller:
  service:
    ## TODO: Change this if no LB are available or you need to use a specific IP for the Controllers
    # externalIPs:
    #   - 192.168.1.2
    #   - 172.10.10.10
    type: LoadBalancer # TODO!: Change this if no LB are available
  # resources:
  #   limits:
  #     cpu: 100m
  #     memory: 90Mi
  #   requests:
  #     cpu: 100m
  #     memory: 90Mi
