apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com-tls
  namespace: example
spec:
  secretName: example-com-tls
  issuerRef:
    name: letsencrypt-production # TODO: Change to your ClusterIssuer
    kind: ClusterIssuer
  commonName: <YOUR_DOMAIN> # TODO: Change to your test domain
  privateKey:
    algorithm: RSA
    size: 2048
  dnsNames:
    - <YOUR_DOMAIN> # TODO: Change to your test domain
